<?php  if ($this->getTarget() == "community" && !Mage::helper('relatedproducts')->isEnterprise()): ?>
<?php if($this->getRelatedProductsCollection()->getSize()): ?>
<div class="aw-related-items">
    <div class="head">
        <h4><?php echo $this->__('Customers Who Bought This Product Also Bought') ?></h4>
    </div>
    <div class="aw-content">
        <p><strong><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" onclick="selectAllAwRelated(this);return false;"><?php echo $this->__('select all') ?></a></strong></p>
        <?php $columnCount = 4; $i=0; foreach($this->getRelatedProductsCollection() as $_item): ?>
        <?php if($i++%$columnCount==0) { ?>
		<ol>
		<?php } ?>
        <li<?php if($_item->isComposite() || !$_item->isSaleable()): ?> class="super-products"<?php endif; ?>>
            <div class="product-images">
				<div class="rpimage">
                	<a href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(56) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" width="56" height="56" /></a>
           		</div>
		    </div>
            <div class="product-details">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="pname"><?php echo Mage::helper('core/string')->truncate($this->htmlEscape($_item->getName()), 30, '...'); ?></a>
                    <?php echo $this->getPriceHtml($_item, true); ?>
					<?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
						<span class="checkbox-container">
						<?php if (!$_item->getRequiredOptions()): ?>
							<input type="checkbox" class="aw-related-checkbox" id="aw-related-checkbox<?php echo $_item->getId() ?>" name="aw_related_products[]" value="<?php echo $_item->getId() ?>" />
						<?php endif; ?>
						</span>
					<?php else: ?>
						<span class="checkbox-container">&nbsp;</span>
					<?php endif; ?>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="aw-link-cart"><?php echo $this->__('Add to Wishlist') ?></a>
                    <?php endif; ?>
            </div>
        </li>
		<?php if($i++%$columnCount==0) { ?>
        </ol>
		<?php } ?>
        <?php endforeach ?>
    </div>
</div>
<script type="text/javascript">
<!--
$$('.aw-related-checkbox').each(function(elem){
    Event.observe(elem, 'click', addAwRelatedToProduct)
});

var relatedAwProductsCheckFlag = false;
function selectAllAwRelated(txt){
    if (relatedAwProductsCheckFlag == false) {
        $$('.aw-related-checkbox').each(function(elem){
            elem.checked = true;
        });
        relatedAwProductsCheckFlag = true;
        txt.innerHTML="<?php echo $this->__('unselect all') ?>";
    } else {
        $$('.aw-related-checkbox').each(function(elem){
            elem.checked = false;
        });
        relatedAwProductsCheckFlag = false;
        txt.innerHTML="<?php echo $this->__('select all') ?>";
    }
    addAwRelatedToProduct();
}

function addAwRelatedToProduct(){
    var checkboxes = $$('.aw-related-checkbox');
    var values = [];
    for(var i=0;i<checkboxes.length;i++){
        if(checkboxes[i].checked) values.push(checkboxes[i].value);
    }
    
    if($('related-products-field')){
        $('related-products-field').value = values.join(',');
    }
    
}
//-->
</script>
<?php endif ?>
<?php endif ?>