<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('') ?>aw_featuredproducts/css/main.css" media="all" />
<?$H = Mage::helper('featuredproducts');?>

<style type="text/css">
	/* CSS */
	
.visios .frameWindow{
	position:absolute;
	height:<?=$H->getDisplay('blockheight')?>px;
}
.visios .visio-frame{
	width:<?=$H->getDisplay('containerwidth')?>px;
	height:<?=$H->getDisplay('containerheight')?>px;
}
#FPSS, #slider{
	width:<?=$H->getDisplay('containerwidth')?>px;
	height:<?=$H->getDisplay('containerheight')?>px;
}
.visios .visio-frame .visio-block{
	width:<?=$H->getDisplay('blockwidth')?>px;
	height:<?=$H->getDisplay('blockheight')?>px;
	text-align:<?=$H->getDisplay('align')?>;
	
}

#slider{
	position:relative;
}

#slider .visio-blinker{
	position:relative;
}
.visios .visio-blinker .visio-frame{
	width:<?=$H->getDisplay('blockwidth')?>px;
	height:<?=$H->getDisplay('blockheight')?>px;
}
A.slider-button{
	height:<?=$H->getDisplay('blockheight')?>px;
}


.product-image{
	margin-right:5px;
}
#slider .dock{
	bottom:0;
	clear:both;
	line-height:48px;
	margin:auto;
	position:absolute;
	vertical-align:bottom;
	width:100%;
}


#FPSS .slider button.form-button{
	float:<?=$H->getDisplay('align')?>;
}

.FPSSError{
	color:red;
	text-align:center;
	padding:30px;
	border:1px solid gray;
}
</style>



