<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
<div class="page-head">
    <h3><?php echo $this->__('Referral Program') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('rewardsref/customer/invite/') ?>" method="post" id="form-validate">
    <?php if($this->hasPredictedSignupPoints()): ?>
    <!-- div>
        <?php echo $this->__("You could up to %s for when your referral signs up.", $this->getPredictedSignupPoints()); ?>
    </div -->
    <?php endif; ?>
    <?php if($this->hasPredictedFirstOrderPoints()): ?>
    <!-- div>
        <?php echo $this->__("You could up to %s for when your referral makes their first order.", $this->getPredictedFirstOrderPoints()); ?>
    </div -->
    <?php endif; ?>
    <fieldset class="group-select" style="margin-bottom: 0px;">
        <input type="hidden" value="Il1NwrpfsCuSmp03" name="form_key"/>
        <h4 class="legend"><?php echo $this->__('Refer a friend') ?></h4>
        <ul>
            <li>
                <div class="input-box">
                    <label for="telephone"><?php echo $this->__('Friend\'s name') ?> <span class="required">*</span></label><br />
                    <input type="text" name="name" value="" title="<?php echo $this->__('Friend\' name') ?>" class="required-entry input-text" id="name" />
                </div>
                <div class="input-box">
                    <label for="fax"><?php echo $this->__('Friend\'s email address') ?> <span class="required">*</span></label><br />
                    <input type="text" name="email" id="email" title="<?php echo $this->__('Friend\'s email address') ?>" value="" class="required-entry input-text" />
                </div>
            </li>
            <li>
                <div>
                    <label for="msg"><?php echo $this->__('Short Message') ?> </label><br />
                    <textarea type="text" name="msg" value="" title="<?php echo $this->__('Short Message') ?>" 
                            class="input-text" id="msg" ></textarea>
                </div>
            </li>
        </ul>
    </fieldset>
    <div class="button-set" style="margin-top:0px">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <!--<a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>-->
        <button class="form-button" type="submit"><span><?php echo $this->__('Send') ?></span></button>
    </div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
</script>
<h2><?php echo $this->__("Referrals"); ?></h2>
<?php $_referred = $this->getReferred();?>
<?php if($_referred->getSize()): ?>
<?php echo $this->getPagerHtml() ?>
<table cellspacing="0" class="data-table" id="referred-friends-table">
    <thead>
        <tr>
            <?php ?><th><?php echo $this->__('Full Name') ?></th><?php ?>
            <th><?php echo $this->__('Email') ?></th>
            <!--<th><?php echo $this->__('Registered?') ?></th>-->
            <th><?php echo $this->__('Status') ?></th>
            <th><?php echo $this->__('Accumulated Earnings') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_referred as $_friend): ?>
            <tr>
                <?php ?><td><?php echo $_friend->getReferralName() ?></td><?php ?>
                <td><?php echo $_friend->getReferralEmail() ?></td>
                <!--<td><?php echo $_friend->getReferralChildId() ? $this->__('yes') : $this->__('no') ?></td>-->
                <td class="a-left"><?php echo $this->getStatusCaption( (int)($_friend->getReferralStatus()) ); ?></td>
                <td><?php echo $this->getAccumulatedReferralPoints($_friend); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->getPagerHtml() ?>
<script type="text/javascript">decorateTable('referred-friends-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You haven\'t invited any friend.'); ?></p>
<?php endif ?>