<?php
/**
 * Morningtime
 * LatestReviews module
 *
 * @category   design_default
 * @package    Morningtime_LatestReviews
 * @copyright  Copyright (c) 2009 Morningtime, http://www.morningtime.com
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Morningtime_LatestReviews_Block_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
    <table class="pager" cellspacing="0">
        <tr>
            <td>&nbsp;</td>
        </tr>
    </table>
<?php endif ?>
