<?php if($this->getConfig('enabled')){ // start enable module?>
	<?php $this->getProducts() ?>
	<?php $_productCollection=$this->getProductCollection() ?>
	<div class="ma-onsaleproductslider-container">
		<?php				
			if ( !$this->getConfig('width_thumbnail') ){
				$w_thumbnail = 135;
			} else {
				$w_thumbnail = $this->getConfig('width_thumbnail');
			}
			if( !$this->getConfig('height_thumbnail') ){
				$h_thumbnail = 135;
			 }
			else {
				$h_thumbnail = $this->getConfig('height_thumbnail');
			}
		?>
		<?php if($this->getConfig('title')){?>
			<div class="box-onsaleproductslider-title"><div class="ma-onsaleproductslider-title"><h2><?php echo $this->getConfig('title')?></h2></div></div>
		<?php }?>
		<?php if(!$_productCollection->count()): ?> 
			<div class="ma-onsaleproductslider">	
				<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
				<ul class="bxslider">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<li class="onsaleproductslider-item">
							<div class="item-inner">
								<div class="box-item">
									<div class="products">
										<article class="product">
										<figure> 
											<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
												<div class="product-image">
													<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(240,240); ?>" width="240" height="240" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
												</div>
												<div class="product-image image-rotator">
													<?php 
													$product = $_product;
													if ($product->getRotatorImage() && $product->getRotatorImage() !='no_selection') {
														//$imageTooltipResize = $this->getResizedUrl($imagetTooltip,600,400);
														$image = Mage::helper('catalog/image')->init($product, 'rotator_image')->resize(240, 240);
													} else {
														$image = Mage::helper('catalog/image')->init($_product, 'small_image')->resize(240, 240);
													}
													?>
													<img src="<?php echo $image ?>" width="240" height="240" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
												 </div>			
											</a>
										</figure>
										</article>
									</div>
									<?php if( $this->getConfig('addtowishlist') || $this->getConfig('addtocompare') ){?>
										<ul class="add-to-links">
										    <?php if( $this->getConfig('addtowishlist')): ?>
											<?php if ($this->helper('wishlist')->isAllow()) : ?>
											    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Wishlist') ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
											<?php endif; ?>
										    <?php endif; ?>
										    <?php if( $this->getConfig('addtocompare')): ?>
											<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Compare') ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
											<?php endif; ?>
										    <?php endif; ?>
										</ul>
									<?php }?>
								</div>
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
							<?php if($this->getConfig('review')): ?>
							    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							<?php endif; ?>
							<?php if( $this->getConfig('show_price') ): ?>
							    <?php echo $this->getPriceHtml($_product, true) ?>
							<?php endif; ?>
							<div class="actions">
							    <?php if ($this->getConfig('addtocart')) { ?>
								<?php if($_product->isSaleable()): ?>
								    <button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
								<?php else: ?>
								    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
							    <?php }?>
							</div>
							<?php if( $this->getConfig('description')){?>
							    <div class="ma-desc">
								<?php if(!$this->getConfig('maxlength')){?>
								    <?php echo nl2br($this->htmlEscape($_product->getShortDescription())) ?>
								<?php } else {?>
								    <?php echo nl2br($this->cut_string_onsaleproductslider($this->htmlEscape($_product->getShortDescription()),$this->getConfig('maxlength'))) ?>			            
								<?php }?>			                    
							    </div>
							<?php }?>
								<?php $i++;?>
							</div>
						</li>                    
					<?php endforeach; ?>
				</ul>

                <script type="text/javascript">
					$jq(document).ready(function(){
					  $jq('.ma-onsaleproductslider-container .bxslider').bxSlider(
						{
						<?php if($this->getConfig('auto')) { ?>
						  auto: true,
						<?php } ?>
						  speed: <?php echo $this->getConfig('speed') ?>,
						  pause: <?php echo $this->getConfig('interval') ?>,			  
						  minSlides: 1,
						  maxSlides: <?php echo $this->getConfig('items_show') ?>,
						  slideWidth: <?php echo $this->getConfig('item_width') ?>,
						  slideMargin:30,
						  infiniteLoop:false,
						<?php if ($this->getConfig('nav_ctrl')) { ?>
						  pager: true,
						<?php } else { ?> 
						  pager:false, 
						<?php } ?>
						<?php if ($this->getConfig('next_back')) { ?>
							controls: true,
						<?php } else { ?>
							controls:false
						<?php } ?>
						}
					  );
					});
				</script>
		<?php endif; ?> 
	</div> 
<?php } ?>


