<?php
/**
 * WDCA - Sweet Tooth
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the WDCA SWEET TOOTH POINTS AND REWARDS 
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth License is available at this URL: 
 *      http://www.wdca.ca/solutions_page_sweettooth/Sweet_Tooth_License.php
 * The Open Software License is available at this URL: 
 *      http://opensource.org/licenses/osl-3.0.php
 * 
 * DISCLAIMER
 * 
 * By adding to, editing, or in any way modifying this code, WDCA is 
 * not held liable for any inconsistencies or abnormalities in the 
 * behaviour of this code. 
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by WDCA, outlined in the 
 * provided Sweet Tooth License. 
 * Upon discovery of modified code in the process of support, the Licensee 
 * is still held accountable for any and all billable time WDCA spent 
 * during the support process.
 * WDCA does not guarantee compatibility with any other framework extension. 
 * WDCA is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to 
 * contact@wdca.ca or call 1-888-699-WDCA(9322), so we can send you a copy 
 * immediately.
 * 
 * @category   [TBT]
 * @package    [TBT_Rewards]
 * @copyright  Copyright (c) 2009 Web Development Canada (http://www.wdca.ca)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

/**
 * Product View Points
 *
 * @category   TBT
 * @package    TBT_Rewards
 * @author     WDCA Sweet Tooth Team <contact@wdca.ca>
 */
?>

<?php
	$rewards = $this->getDistriRewards();
	$ruleOptions = $this->getRedeemableOptions();
	$ruleMap = $this->getApplicableRulesMap();
	$c = Mage::helper('rewards/currency');
	$pid = $this->getProduct()->getId();
	$show_reduced_price = true;
	$show_discount_in_uses_selector = true;
	$show_slider = true;
	// TODO: hide the redemption drop down and show the slider with a minimum value of "0"
	//$use_slider_for_single_redemption = true;
?>

<script type="text/javascript">

// Configurations ///////////////
var show_lowest_price = <?php echo $show_reduced_price ? 'true' : 'false'; ?>;
var show_discount_in_uses_selector = <?php echo $show_discount_in_uses_selector ? 'true' : 'false'; ?>;

// Other PHP content ///////////////
var currency_map  = <?php echo $this->getCurrencyMapJson(); ?>;

var original_product_price = "<?php echo $this->getOriginalPrice(); ?>";
var rule_options = <?php echo json_encode($ruleMap); ?>;
var base_product_id = <?php echo $pid; ?>;
var is_configurable_product = <?php echo (int)$this->getProduct()->isConfigurable(); ?>;
var customer_points = <?php echo ($this->getCurrentCustomer() ? json_encode($this->getCurrentCustomer()->getPoints()) : "false"); ?>;
var do_hide_old_price = false;
var default_guest_points = <?php echo $this->getDefaultGuestPoints(); ?>;

var new_price_dom_id = 'product-price-<?php echo $pid; ?>';
var old_price_dom_id = 'old-price-<?php echo $pid; ?>';
var slider_mode = <?php echo $show_slider ? 'true' : 'false'; ?>;
</script>



<?php if(sizeof($ruleOptions) > 0): ?>
<script type="text/javascript">
	document.observe("dom:loaded", function() {
		  // add listener to the config select box if it exists
		optionsPrice.productPriceBeforeRedemptions = optionsPrice.productPrice;
	
	    Form.getElements('product_addtocart_form').each(
	        function(formElem){
	            if(formElem.type == "select-one") { // || formElem.type == 'text'
	                formElem.observe("change", function(e) {
	                	updateUsesInterface();
	                });
	            }
	        }
	    );
	  
	});
    function updateUsesInterface() {
		var rule_id = $('redemption_rule').value;
        if(slider_mode) {
            feignPriceChange(rule_id);
            rSlider.changeRule(rule_id);
            rSlider.changeRule(rule_id); // for some reason this needs to run twice or else the Slider doesn't work...
        } else {
            if(formElem.id == 'redemption_rule_uses') {
                feignPriceChange(rule_id);
            } else if(formElem.id == 'redemption_rule') {
                updateRemptionUsesSelector(rule_id, false);
                feignPriceChange(rule_id);
    			updateRemptionUsesSelector(rule_id, false);
    		} else {
                var val = $('redemption_rule_uses').value;
    			updateRemptionUsesSelector(rule_id, val);
                feignPriceChange(rule_id);
    			if(formElem.id.indexOf("attribute") == 0) {
    				updateRemptionUsesSelector(rule_id, val);
    			} else {
    				updateRemptionUsesSelector(rule_id, false);
    			}
    		}
        }
    }
    function getRedemptionUses() {
        var uses;
        if(slider_mode) {
            uses = rSlider.getUses();
        } else {
        	uses = $('redemption_rule_uses').value;
        }
        return uses;
    }
</script>
<?php endif; ?>

<?php if($this->doShowRedeemer() || sizeof($rewards) > 0): ?>
<div class="product-view-points">
	<?php if($this->doShowRedeemer()): ?>
	<div class="divider"></div>
	<div class="redeem_section">
		<span class="use_points">
			<?php echo $this->__('Use Your Points') . ':'; ?>
		</span>
		<select name="redemption_rule" id="redemption_rule" 
			class="redemption_selector validate-can_use_points validate-has_enough_points">
			<option value="" selected="selected"></option>
			<?php foreach ($ruleOptions as $ruleOption): ?>
				<?php if(isset($ruleOption['rule_id'])): ?>
					<option value="<?php echo $ruleOption['rule_id']; ?>">
						<?php echo $ruleOption['caption']. " (". $this->__('costs') ." ". $ruleOption['points'] .")"; ?>
					</option>
				<?php endif; ?>
			<?php endforeach; ?>
		</select>
		<div id="redemption_rule_uses_container" class="redemption_uses_container" style="display:none;">
			<?php if ($show_slider): ?>
				<div class="slider" onmouseup="sliderNotSliding()">
					<table cellspacing="0" cellpadding="0">
						<tbody>
							<tr>
								<td>
									<div class="sliderRail" id="sliderRail">
									   <a style="left: 0%;" class="sliderHandle ui-slider-handle ui-state-default" id="sliderHandle"
											onmousedown="sliderSliding()"  
											onmouseup="sliderNotSliding()"></a>
									</div>
								</td>
								<td valign="top">
									<div id="sliderCaption" class="sliderCaption" >
										<?php echo ''; ?>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					<input type="hidden" name="redemption_uses" id="redemption_rule_uses"/>
				</div>
				<script type="text/javascript">
					document.observe("dom:loaded", function() {
						usesContainer = $('redemption_rule_uses_container');
						rSlider = new PointsSlider('sliderHandle', 'sliderRail', 'sliderCaption', 'redemption_rule_uses');
					});

					// Functions for changing the cursor on the slider
					function sliderSliding() {
						$('sliderRail').addClassName('sliderRail-sliding'); 
						$('sliderHandle').addClassName('sliderHandle-sliding');
					}

					function sliderNotSliding() {
						$('sliderRail').removeClassName('sliderRail-sliding'); 
						$('sliderHandle').removeClassName('sliderHandle-sliding');
					}
				</script>
			<?php else: ?>
				<select class="redemption_uses_selector" 
				 		id="redemption_rule_uses" name="redemption_uses">
				</select>
				<span class="redemption_rule_uses_caption" id="redemption_rule_uses_caption" ></span>
					
				<script type="text/javascript">
					document.observe("dom:loaded", function() {
						usesSelect = $('redemption_rule_uses'); 
						usesCaption = $('redemption_rule_uses_caption'); 
						usesContainer = $('redemption_rule_uses_container');
					});
				</script>
			<?php endif; ?>
		</div>
	</div>
	<?php endif; ?>
	
	<?php if(sizeof($rewards) > 0): ?>
	<div class="divider"></div>
	<div class="distri_section">
		<?php foreach ($rewards as $reward_currency => $reward_amount): ?>
			<div class="you_will_earn">
				<?php $points_summary = $this->getPointsString($reward_amount, $reward_currency); ?>
				<?php echo $this->__('You will earn %s for buying this product', $points_summary); ?>
			</div>
			
			<?php $img_url = $this->getPointsImgUrl($reward_amount, $reward_currency); ?>
			<?php $imgPath = Mage::getModel('rewards/currency')->load($reward_currency)->getImage(); ?>
			<?php if(!empty($imgPath)): ?>
				<img src="<?php echo $img_url; ?>" class="points_image points_currency_image-<?php echo $reward_currency?>"/>
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
	<?php endif; ?>
</div>
<div class="divider"></div>
<?php endif; ?>