<?php 
/**
 * @category   Netz98
 * @package    Netz98_Raffle
 * @author     Daniel Nitz <d.nitz@netz98.de>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div class="raffle-box">
	<div class="raffle-text">
		<p>Enter our <strong>great raffle</strong> and win <strong>great prices</strong>! First price is this brand new <strong>Apple MacBook Pro</strong> with 2GHz Intel Core Duo Prozessor and 1 GB RAM.</p>
		<p>Application deadline is 01.10.2009. Winners will be drawn by 10.10.2009.</p>
		<p><strong>Good luck!</strong></p>
    </div>
	<div class="raffle-form">
        <?php echo $this->getChildHtml('raffle_form') ?>
    </div>
</div>