<script type="text/javascript" 
	src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>js/velite/teaserbox/swfobject.js">
</script>

<script type="text/javascript">
var psVars = {
    host: "<?= $this->getTeaserboxXmlUrl(); ?>"
}

var psParams = {
	menu:false,
	bgcolor: "FFFFFF",
	wmode: "opaque"
}

swfobject.embedSWF("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>js/velite/teaserbox/teaserbox.swf", 
	"teaserboxBox", 
	"142", 
	"142", 
	"9.0.0",
	"<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>js/velite/teaserbox/expressInstall.swf",
	psVars, 
	psParams
);
</script>

<?php 
	echo $this->getTeaserboxDiv();
?>