<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('Easy Stock Upload Tool')?></h3></td>

            <td class="a-right">
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">

<?php
		// Bugfix 26/08/2009 reported by PN:
		// Magento requires that you expilicitly tell it to make getUrl calls use ssl.
		// some magento installations may not use SSL on admin areas however; therefore it is vital that we
		// first check the settings to see if the calls on this page need to be made via SSL or not.
		
		$is_ssl = (Mage::getStoreConfig('web/secure/use_in_adminhtml') == 1)? true : false;
									
?>
			

		<form id="edit_form_1" name="edit_form_1" method="post" action="<?=$this->getUrl('*/*/download',array('_secure' => $is_ssl))?>" target="downloader2" enctype="multipart/form-data">
		<input type="hidden" name="form_key" id="form_key" value="<?=Mage::getSingleton('core/session')->getFormKey() ?>">
		 <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Step One: CSV Download')?></h4>
        <fieldset id="my-fieldset">
		<?php echo $this->__('To begin, click the button below. You will be prompted to save a CSV file. Open this file in excel and in the column with the heading \'stock level after update\' enter the level of stock found during the stock check. Repeat as necessary, then save the file and continue below. Alternatively, leave the \'stock level after update\' column empty, and instead enter a value under the amount you want to change stock up or down by in the \'Add to stock level\' or \'Remove from stock level\'  columns of each updated product. Please note that you should only enter a value in ONE of the three columns for each line, but you can skip a line if you do not wish to alter the stock on this product.')?><br><br>									<center>					
		<table cellspacing="0" class="form-list">
							<tr>
								<td colspan="2">								<button type="submit" name="submit" value="Process File!">
								<span>Download File</span>
								</button>
									<iframe id="downloader2" name="downloader2" src="about:blank" style="display:none;" frameborder="1"></iframe>
								</td>
							</tr>								
						</table></center>
						</fieldset>
								</form>
								
								
	<form id="edit_form" name="edit_form" method="post" action="<?=$this->getUrl('*/*/upload',array('_secure' => $is_ssl))?>" target="downloader" enctype="multipart/form-data">
	
		<input type="hidden" name="form_key" id="form_key" value="<?=Mage::getSingleton('core/session')->getFormKey() ?>">
		 <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Step Two: Upload Changes and process file')?></h4>
        <fieldset id="my-fieldset">
		<?php echo $this->__('Once you have edited the CSV file output in step one, please select the file below and click \'Process File\'. A progress bar should then appear and show you the status of the stock update.')?><br><br>														
			<center>	<table cellspacing="0" class="form-list" style="border:1px solid #000000 !important; padding:5px;">
							<tr>
								<td class="label"><?php echo $this->__('Upload your file')?></td>
								<td class="input-ele"><input type="file" name="csvfile">
								</td>
							</tr>		
							<tr>
								<td colspan="2">							<iframe id="downloader" name="downloader" src="about:blank" style="width:400px;height:40px;overflow:hidden;display:show;border:1px solid #999999;background-color:#FFFFFF;" frameborder="1"></iframe></center>
</td>
							</tr>								
							<tr>
								<td colspan="2" style="text-align:center">
								<button class="scalable save" type="submit" name="submit" value="Process File!">
								<span>Process File</span>
								</button>
								</td>
						</table></center>
						</fieldset>
								</form>
								
	</div>

		
	<script type="text/javascript">
				var editForm1 = new varienForm('edit_form_1');
				var editForm = new varienForm('edit_form');
			</script>
			
			
