<?php $storeViews = Mage::app()->getStores(); ?>
<?php
$labels = array(
    'tennis'        => __('Tennis'),
    'squash'        => __('Squash'),
    'badminton'     => __('Badminton'),
    'beachtennis'   => __('Beach tennis'),
);
?>
<div class="ma-nav-mobile-container visible-xs">
    <div class="box-padding">
        <div class="navbar">
            <div id="navbar-store-inner" class="navbar-inner navbar-inactive">
                <div class="menu-mobile">
                    <a class="btn btn-navbar navbar-toggle">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <span class="brand navbar-brand"><?php echo $this->__('Stores') ?></span>
                </div>
                <ul id="ma-store-mobilemenu" class="mobilemenu">
                    <?php $i = 0; ?>
                    <?php foreach($storeViews as $_id => $_store): ?>
                        <li class="level0 nav-<?php print $i + 1; ?> level-top parent<?php ($i == 0 ? ' first' : '') ?>">
                            <a href="<?php print Mage::app()->getStore($_id)->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>" class="level-top" title="<?php print Mage::app()->getStore($_id)->getFrontendName() ?>">
                                <span><?php print $labels[Mage::app()->getStore($_id)->getCode()] ?></span>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="storenav-container visible-lg visible-md">
    <div id="pt_storemenu" class="pt_storemenu">

        <?php $i = 0; ?>
        <?php foreach($storeViews as $_id => $_store): ?>
            <?php $s = $_id . ' - ' . Mage::app()->getStore()->getCode() . ' - ' . Mage::app()->getStore($_id)->getCode(); ?>
            <?php $active = (Mage::app()->getStore()->getCode() == Mage::app()->getStore($_id)->getCode()) ? ' active' : ''; ?>
            <div id="pt_menu_store_<?php print Mage::app()->getStore($_id)->getCode(); ?>" class="pt_menu_no_child nav-<?php print Mage::app()->getStore($_id)->getCode(); ?> pt_store_menu <?php print $active; ?>" >
                <div class="parentMenu">
                    <a href="<?php print Mage::app()->getStore($_id)->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>" title="<?php print $labels[Mage::app()->getStore($_id)->getCode()] ?>" class="level-top">
                        <span><?php print $labels[Mage::app()->getStore($_id)->getCode()] ?></span>
                    </a>
                </div>
            </div>
            <?php $i++; ?>
        <?php endforeach; ?>

        <div class="clearBoth"></div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    <?php /*
    var CUSTOMMENU_POPUP_EFFECT = <?php echo (int)Mage::getStoreConfig('custommenu/popup/effect')?>;
    var CUSTOMMENU_POPUP_TOP_OFFSET = <?php echo (int)Mage::getStoreConfig('custommenu/popup/top_offset')?>;
    */ ?>
    //]]>
</script>
