<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Islider
 * @copyright  Copyright (c) 2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>

<?php if($this->canDisplay() && $this->getSlides()->getSize()) : ?>
<div class="awis-block awis-r-default awis-effect-<?php echo $this->getSwitchEffect() ?> awis-rpr-default-horizontal awis-block-<?php echo $this->getAWISBlock()->getData('id') ?>" id="<?php echo $this->getUniqueBlockId() ?>" style="<?php echo $this->getContainerStyleString() ?>">
    <div class="awis-slides-container">
        <?php $_i = 0 ?>
        <?php foreach($this->getSlides() as $slide) : ?>
        <div style="<?php echo $this->getContainerStyleString() ?>" id="<?php echo $this->getUniqueBlockId() ?>div<?php echo $_i ?>" class="awis-r-default-item">
            <?php if($slide->getData('url')) : ?>
            <a href="<?php echo $this->getUrl('awislider/link/out', array('sid' => $slide->getData('id'))) ?>"<?php if($slide->getData('new_window')) : ?> target="_blank"<?php endif ?><?php if($slide->getData('nofollow')) : ?> rel="nofollow"<?php endif ?>>
            <?php endif ?>
                <img src="<?php echo ($slide->getUriLocation()) ?>" title="<?php echo htmlspecialchars($slide->getData('title')) ?>" alt="<?php echo htmlspecialchars($slide->getData('title')) ?>" border="0" />
            <?php if($slide->getData('url')) : ?>
            </a>
            <?php endif ?>
        </div>
        <?php $_i++ ?>
        <?php endforeach ?>
    </div>
    <div class="awis-slides-controls"<?php if($_i <= 1) : ?> style="display: none"<?php endif ?>>
        <div class="awis-c-left">
            <button class="button" onclick="<?php echo $this->getUniqueBlockId() ?>.previous();"></button>
        </div>
        <div class="awis-c-center">
            <?php for($_j = 0; $_j < $_i; $_j++) : ?>
            <button class="button<?php echo $_j==0 ? ' awis-s-current' : '' ?>" onclick="<?php echo $this->getUniqueBlockId() ?>.show(<?php echo $_j ?>);"></button>
            <?php endfor ?>
        </div>
        <div class="awis-c-right">
            <button class="button" onclick="<?php echo $this->getUniqueBlockId() ?>.next();"></button>
        </div>
    </div>
</div>
<script type="text/javascript">
    new awiSlider('<?php echo $this->getUniqueBlockId() ?>', {
        blockId: '<?php echo $this->getUniqueBlockId() ?>',
        effect: '<?php echo $this->getSwitchEffect() ?>',
        slidesCount: '<?php echo $_i ?>',
        animationSpeed: '<?php echo $this->getAnimationSpeed() ?>',
        firstFrameTimeout: '<?php echo $this->getFirstFrameTimeout() ?>',
        autohideNavigation: '<?php echo $this->getAutohideNavigation() ?>',
        needCalculateWH: <?php echo $this->getWidth() && $this->getHeight() ? '0' : '1' ?>
    });
</script>
<?php endif ?>
