<?php
    /**
     * aheadWorks Co.
     *
     * NOTICE OF LICENSE
     *
     * This source file is subject to the EULA
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://ecommerce.aheadworks.com/LICENSE-M1.txt
     *
     * @category   AW
     * @package    AW_Onsale
     * @copyright  Copyright (c) 2009-2010 aheadWorks Co. (http://www.aheadworks.com)
     * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
     */
?>
<?php if ( $this->isShow() ): ?>
        <?php if (isset($_SERVER['HTTP_USER_AGENT']) && (strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE') !== false)): ?>
                <style type="text/css">DIV.onsale-product-container * { MARGIN: 0px; }</style>
        <?php endif; ?>
        <?php $__Position = $this->getPosition(); ?>
        <table ondblclick="if(product_zoom)product_zoom.toggleFull.bind(product_zoom)();" width="100%" cellspacing="0" cellpadding="0" class="onsale-product-container"<?php if (in_array($__Position, array('BL', 'BC', 'BR'))): ?> style="BOTTOM: 0px;"<?php endif; ?>>
                <tr>
                        <td width="100%">
                        	<div align="<?php if (($__Position == 'TC') or ($__Position == 'BC')) print 'center'; if (($__Position == 'TR') or ($__Position == 'BR')) print 'right'; ?>">
                                <div class="onsale-product-label-image" style="<?php print $this->getImageSizeHtml(); ?> BACKGROUND-IMAGE: url('<?php print $this->getImageUrl(); ?>');">
                                        <table class="<?php echo  $this->getType() ?>-onsale-product-label-text" width="100%" height="100%" cellspacing="0" cellpadding="0">
                                                <tr>
                                                        <td align="center" valign="middle">
                                                                <?php print $this->getFormatedText() ?>
                                                        </td>
                                                </tr>
                                        </table>
                                </div>
							</div>
                        </td>
                </tr>
        </table>
<?php endif; ?>