<?php if (Mage::getStoreConfig('ajax_pro/general/enabled') && Mage::getStoreConfig('ajax_pro/addToCart/enabledForm')) :?>
<div id ="ajaxpro-addtocart-form" style="display:none">
    <p class="ajaxpro-message"></p>
	<button class="ajaxpro-continue-button button"><span><span><?php echo Mage::helper('ajaxpro')->__('Continue shopping')?></span></span></button>
    <p class="ajaxpro-or"><?php echo Mage::helper('ajaxpro')->__('or')?></p>
	<button class="ajaxpro-continue-button button" onclick="setLocation('<?php echo Mage::getUrl('checkout/cart/')?>')"><span><span><?php echo Mage::helper('ajaxpro')->__('View cart & checkout');?></span></span></button>
</div>
<?php endif; ?>