<?php if (Mage::getStoreConfig('ajax_pro/general/enabled') && Mage::getStoreConfig('ajax_pro/addToCompare/enabledForm')) :?>
<div id ="ajaxpro-addtocompare-form" style="display:none">
    <p class="ajaxpro-message"></p>
		<button class="ajaxpro-continue-button button"><span><span><?php echo Mage::helper('ajaxpro')->__('Continue shopping')?></span></span></button>
    <p class="ajaxpro-or"><?php echo Mage::helper('ajaxpro')->__('or')?></p>
	<button class="ajaxpro-continue-button button" onclick="popWin('<?php echo $this->helper('catalog/product_compare')->getListUrl() ?>','compare','width=800,height=600,resizable=yes,scrollbars=yes')"><span><span><?php echo Mage::helper('ajaxpro')->__('Compare Items');?></span></span></button>
</div>
<?php endif;?>