<?php if (Mage::getStoreConfig('ajax_pro/general/enabled') && Mage::getStoreConfig('ajax_pro/general/enabledNoticeForm')) :?>
<div id ="ajaxpro-notice-form" style="display:none">
    <p class="ajaxpro-message"></p>
	<button class="ajaxpro-continue-button button"><span><span><?php echo Mage::helper('ajaxpro')->__('Continue shopping')?></span></span></button>
    <!--
    <p class="ajaxpro-or"><?php echo Mage::helper('ajaxpro')->__('or')?></p>
    <a class="ajaxpro-action-button button" href="#"><span><?php echo Mage::helper('ajaxpro')->__('Redirect') ?></span></a>
    -->
</div>
<?php endif; ?>